version: '3.8'

services:
  bot:
    build: .
    environment:
      - PYTHONPATH=/app
      - BOT_TOKEN=${BOT_TOKEN}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
    command: >
      sh -c "uvicorn web.routes:app --host 0.0.0.0 --port 8080 & 
      python -m bot.main_handler"
    ports:
      - "8080:8080"
    restart: unless-stopped
