version: '3.8'

services:
  bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PORT=8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
    restart: unless-stopped
