version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - file_storage:/app/uploads
    environment:
      - STORAGE_PATH=/app/uploads

volumes:
  file_storage:
