version: '3.8'

services:
  bot:
    build: ./docker
    ports:
      - "8080:8080" # Changed port
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
