services:
  - name: file-share-bot
    ports:
      - port: 8080
        http_path: /healthz
    routes:
      - /:8080
    env:
      - name: BOT_TOKEN
        value: "{{.KOYEB_SECRET_BOT_TOKEN}}"
      - name: DATABASE_URL
        value: "{{.KOYEB_SECRET_DATABASE_URL}}"
      - name: PORT
        value: "8080"
    docker:
      image: koyeb/file-share-bot:latest
    healthchecks:
      liveness:
        path: /healthz
        port: 8080
        timeout: 10
