name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: koyeb/action@v1
        with:
          service: file-share-bot
          token: ${{ secrets.KOYEB_TOKEN }}
