name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: koyeb/action@v1
        with:
          service: your-service-name
          token: ${{ secrets.KOYEB_TOKEN }}
